# Generated by Django 3.2.6 on 2021-08-11 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='name_of_ingredient',
            new_name='name_of_the_ingredient',
        ),
    ]
