# Generated by Django 3.2.6 on 2021-08-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0002_rename_name_of_ingredient_ingredient_name_of_the_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(null=True, to='recipes_app.Ingredient'),
        ),
    ]
